# Generated by Django 5.0.6 on 2024-05-08 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_post_user_alter_post_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='created_at',
        ),
    ]
